pipelines:
  default:
    - step:
        name: Build and run tests for PHP 5.6
        image: php:5.6-cli
        script:
            - phpize
            - ./configure --enable-ev
            - make test
    - step:
        name: Build and run tests for PHP 7.1
        image: php:7.1-cli
        script:
            - phpize
            - ./configure --enable-ev
            - make test
